#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 hostname root_dir"
  exit 1
fi

host=$1
path=$2
port=8000

target_url="http://localhost:${port}/"
echo -e 'Wait server connecting, then open url:'
echo -e "\t${target_url}\n"

ssh -L ${port}:localhost:${port} ${host} -t "python3 -m http.server ${port} --bind 0.0.0.0 --directory ${path}"
