unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" basic config
set cursorline
set relativenumber
set hlsearch

" Python formatting
au BufNewFile,BufRead *.py,*.md
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set fileformat=unix |

colorscheme apprentice

" Key binding
nnoremap <Leader>t :25Le<CR>
nmap <silent><Leader>g :call setbufvar(winbufnr(popup_atcursor(split(system("git log -n 1 -L " . line(".") . ",+1:" . expand("%:p")), "\n"), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })), "&filetype", "git")<CR>

" brew install ripgrep
set grepprg=rg\ --vimgrep\ --smart-case
