let $LANG = 'en_US'

" basic config
set cursorline
set relativenumber
set hlsearch
set noswapfile
set signcolumn=no

" Python formatting
au BufNewFile,BufRead *.py
    \ set textwidth=120 |
    \ set expandtab |
    \ set autoindent |
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set fileformat=unix |

call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

colorscheme apprentice

" Key binding
nmap <silent><Leader>g :call setbufvar(winbufnr(popup_atcursor(split(system("git log -n 1 -L " . line(".") . ",+1:" . expand("%:p")), "\n"), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })), "&filetype", "git")<CR>
nmap <silent> gd <Plug>(coc-definition)
