# Dictionary
alias dq="open https://www.oxfordlearnersdictionaries.com/definition/english"

alias att_gravity="kinit;ssh gravity -t 'bash /root/.att_devbox.sh'"
#alias att_mapupdate="kinit;ssh mapupdate -t 'bash /root/.att_devbox.sh'"
alias att_mapupdate="kinit;ssh new_mapupdate -t 'bash /root/.att_devbox.sh'"







