export LANG=en_US.UTF-8

alias emacs="emacs -nw"

alias att_e2e="kinit;ssh e2e -t 'tmux att'"
alias att_gravity="kinit;ssh gravity -t 'tmux att'"
alias att_mapupdate="kinit;ssh mapupdate -t 'tmux att'"







